name: OptikLink Auto Cookie KeepAlive

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 1 小时自动跑一次
  repository_dispatch:
    types: [keepalive_trigger]
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install playwright axios form-data
          npx playwright install chromium --with-deps

      - name: Run Script
        env:
          USER_COOKIE: ${{ secrets.USER_COOKIE }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node login.js
